services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_VHOST=/
      - RABBITMQ_QUEUE=eventual
      - DB_PATH=/app/data
    networks:
      - app-network
    volumes:
      - app_data:/app/data:rw
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    build:
      context: rabbitMQ
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    networks:
      - app-network
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  app-network:
    driver: bridge
volumes:
  app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
